name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions: # 新增权限声明
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false # 禁用默认凭证

      - name: Verify file structure
        run: |
          ls -lR src/_includes
          [ -f src/_includes/base.njk ] || exit 1

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build site
        run: |
          npx @11ty/eleventy \
            --input=src \
            --output=11ty-site \
            --formats=njk,md,css \
            --pathprefix=/
          echo "Disable Jekyll" > ../11ty-site/.nojekyll

      - name: Validate build output
        run: |
          [ -f 11ty-site/index.html ] || exit 1
          grep -q "皓魄流霜" 11ty-site/index.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          force_orphan: true  # clear history
          github_token: ${{ secrets.GH_PAGES_TOKEN }}
          publish_dir: ./11ty-site